### ISSUE TITLE
Intelligent Icon creator command

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#107]
### Description

As per discussion here: https://github.com/Spomky-Labs/pwa-bundle/discussions/100#discussioncomment-8692986

**Comment by Spomky** [comment]
Icon mgmt is a bit boring....
The user shall:

* Use the command to generate icons at the correct size
* Copy / Paste the output and indent correctly in the correct section

Repeat for the application or each shortcut.

```yaml
# Configuration (today)
pwa:
    manifest:
        ...
        icons:
            - src: "icons/logo.svg"
              sizes: [0]
            - src: "icons/logo_48x48.png"
              sizes: [48]
            - src: "icons/logo_96x96.png"
              sizes: [96]
            - src: "icons/logo_144x144.png"
              sizes: [144]
            - src: "icons/logo_180x180.png"
              sizes: [180]
            - src: "icons/logo_256x256.png"
              sizes: [256]
            - src: "icons/logo_512x512.png"
              sizes: [512]
```

This could be drastically simplified by formatting/converting the files during the compilation time

```yaml
# Expected configuration
pwa:
    manifest:
        ...
        icons:
            - src: "icons/logo.svg"
              formats:
                  # Tuples format: sizes
                  svg: [0]
                  png: [48, 96, 144, 180, 256, 512]
```

During the compilation, the bundle should:

* Create the icons at the expected sizes and formats
* Populate the manifest accordingly

For dev/test, the images are not converted and formats are merged.
The browser will moan about that in these envs, but not in production.

When done, this will be on a similar way for #66
