### ISSUE TITLE
allow parameters in WarmCache

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#114]
### Description

Currently routes in the warm_cache_urls are limited to routes without parameters:

```yaml
            warm_cache_urls:
                - 'app_homepage'
                - '_api_/items{._format}_get_collection'
```

### Example
```yaml
            warm_cache_urls:
                - route: 'planet_show'
                  params: ['code' => 'earth']

                - 'app_homepage'
                - '_api_/items{._format}_get_collection'
```

That would match #[Route("/show/{code}", name: 'planet_show']

Arguably, the route parameters could be an array of route parameters

```yaml
 warm_cache_urls:
                - route: 'planet_show'
                  params: 
                       - ['code' => 'earth']
                       - ['code' => 'jupiter']
                       - ['code' => 'mercury']
```

Of course, this is related to #113  and the CachingStrategy attribute idea.

Obviously, we could put the full urls in the configuration, but it's much better to work with routes, since the urls change.

**Comment by Spomky** [comment]
This is already possible for any  URL in the configuration file. See https://pwa.spomky-labs.com/the-manifest/shortcuts#url-parameter.
The follwing config is valid.
```yaml
            warm_cache_urls:
                - path: 'planet_show'
                   params:
                       code: 'earth'
```
