### ISSUE TITLE
page_cache requires a regex, even if url provided

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#125]
### Version(s) affected

1.1.x

### Description

The page_cache: has been changed to page_caches, and takes an array of page_cache.

But simply changing the example of what's listed in the documentation doesn't work, because it requires a cache_name and regex key.   Both should have sensible defaults.  

### How to reproduce

```yaml
        workbox:
            page_caches:
                - 
                    cache_name: staleWhileRevalidate # maybe make this the strategy name by default?
                    strategy: 'staleWhileRevalidate'
                    broadcast: true
                    broadcast_headers:
                        - 'X-App-Cache'
                    regex: / # what should this be
                    urls:
                    - 'app_homepage'
```

### Possible Solution

The demo and documentation both need to be updated to the latest version of 1.1.x

```yaml
workbox:
            page_cache:
                strategy: 'staleWhileRevalidate'
                broadcast: true
                broadcast_headers:
                    - 'X-App-Cache'
                urls:
                - 'app_homepage'
```

**Comment by Spomky** [comment]
The changes are not well documented (I am updating the doc at the moment).

URLs is a list of precached pages and shall be under the regex otherwise it will never match.
I think a verification should be added here to avoid confusion

**Comment by Spomky** [comment]
I am wondering how to simplify the config here.
For example, if you want to cache all `/pages/.*` routes using the network first strategy, you have to write the following config:

```yaml
pwa: ​
    serviceworker: ​
        enabled: true​
        src: 'sw.js' ​
        workbox:​
            page_caches:​
                - cache_name: 'pages'​
                  regex: "\/pages\/.*"​
                  urls: ​
                    - 'app_tos'
                    - 'app_legal'
                    - 'app_features'
```

I think first I will change `regex` into `matchCallback` and allow any type of callback as shown on the [Workbox documentation](https://developer.chrome.com/docs/workbox/modules/workbox-routing).

* All pages the user navigates to: `({request}) => request.mode === 'navigate'`
* A specific page: `({url}) => url.pathname === '/special/url'`
* Using `url` properties: `({url}) => url.origin === 'https://api.foo.com'`
* A regex: `'\/pages.*'` or `new Regexp('\/pages.*')` (quotes are important!)

Next, I will create kind of recipes to ease the config:
```yaml
pwa: ​
    serviceworker: ​
        enabled: true​
        src: 'sw.js' ​
        workbox:​
            page_caches:
                - recipe: 'navigation"
                  urls: 
                      - ...

# Will be converted into
pwa: ​
    serviceworker: ​
        enabled: true​
        src: 'sw.js' ​
        workbox:​
            page_caches:​
                - cache_name: 'page_cache_recipe_0'​
                  matchCallback: "({request}) => request.mode === 'navigate'"​
                  urls: ​
                    - ...
```
