### ISSUE TITLE
allow maxAge to be configured with human-readable strings

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#129]
### Description

Since PHP will [parse standard time strings](https://www.php.net/manual/en/function.strtotime.php), instead of converting maxAge to something human readable in the debug toolbar, what about putting the human-readable string in the yaml.

### Example

```yaml
pwa:
    serviceworker:
        enabled: true
        src: "sw.js"
        workbox:
            image_cache:
                enabled: true
#                max_age: 2_592_000 # 30 days
                max_age: 30 days
                max_entries: 200
                regex: '/\.(png|jpe?g|svg|webp)$/'
```
