### ISSUE TITLE
Add a reference or notes key to screenshot record

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#136]
### Description

I'd like to know where the screenshot came from. 

```yaml
pwa:
    manifest:
        enabled: true
        screenshots:
            - "images/screenshot-feature1.png"
            - 
              src: "images/screenshot-feature2.png"
              platform: "android"
              type: "inmage/png"
            -
              src: "images/screenshot-feature3.png"
              label: "Feature #3 in action"
              form_factor: "narrow"
```

### Example

```yaml
pwa:
    manifest:
        enabled: true
        screenshots:
            - 
              src: "images/screenshot-feature2.png"
              reference: https://example.com/login
              platform: "android"
              type: "image/png"
            -
              src: "images/screenshot-feature3.png"
              reference: https://example.com/article/workflow
              label: "Feature #3 in action"
              form_factor: "narrow"
```
