### ISSUE TITLE
Extract label from title metatag in screenshots

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#137]
### Description

```
bin/console pwa:create:screenshot https://127.0.0.1:8013/product/25 -o floppy-disk
```

```yaml
pwa:
  manifest:
    screenshots:
      -
        src: floppy-disk/screenshot-1200x1100.png
        width: 1200
        height: 1100
        type: image/png

```

### Example

I would like to see the label key filled with whatever's in the <title> tag of the HTML page that panther scrapes.

```
pwa:
  manifest:
    screenshots:
      -
        src: floppy-disk/screenshot-1200x1100.png
        label: "Floppy Disk Details"
        width: 1200
        height: 1100
        type: image/png
```
