### ISSUE TITLE
changes to pwa.yaml require manual cache clearning

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#145]
### Version(s) affected

1.1.x

### Description

Changes to config/packages/pwa.yaml are not reflected when refreshing /sw.js unless the cache is manually cleared.

### How to reproduce

go to /sw.js
change a regex or something
refresh /sw.js (no changes)
refresh again (changes shown)

### Possible Solution

I might be because sw.js is itself cached with a cacheFirst strategy, so the first time it's cached.

**Comment by Spomky** [comment]
Normally, the service worker is not served by the cacheFirst rule. 
There is an option to enable/disable the browser cache:https://pwa.spomky-labs.com/the-service-worker/configuration#cache

**Comment by Spomky** [comment]
Hi @tacman,

Is this issue still a problem?
With the option `skip_waiting` a new service worker is loaded immediatly and the cache will be discarded.

```yaml
pwa:
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
```
