### ISSUE TITLE
Document how to cache an external library

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#148]
### Description

I found a good javascript library for making mobile apps, onsenui, but I can't get it to work with AssetMapper

https://github.com/symfony/symfony/discussions/54342

Instead, I'm adding the script tag at the top, which works, but of course requires an internet connection.  How would I add this as a pre-cached URL and CacheOnly, so it would work with offline?

    <script src="https://cdn.jsdelivr.net/npm/onsenui@2.12.8/js/onsenui.min.js"></script>

In particular

>  Please note that you can refer to any URLs, but only URLs served by your application will be cached.

on https://pwa.spomky-labs.com/the-service-worker/workbox/warm-caching

**Comment by Spomky** [comment]
Something like as follows should work (not tested)

```yaml
pwa:
    serviceworker:
        enabled: true
        src: "sw.js"
        workbox:
            resource_caches:
                - match_callback: 'origin: cdn.jsdelivr.net'
                  strategy: 'CacheFirst'
                  preload_urls: # Optional, but you are now sure the library is preloaded even if used on another page the user never met before
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/js/onsenui.min.js'
```

**Comment by tacman** [comment]
I'm revisiting this, because last night the jsdelivr cdn was down for several hours because the certificate had expired.  LOTS of sites broke, and I was reminded that at least for existing users (not new visitors) if I had this implemented it would have continued to work for a bit.

It does not appear that this is working, though, as the other assets show that they are delivered via the service worker, but not the jsdelivr ones.

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/7f698ea2-87be-4b5f-ad92-dded673e7698)

```yaml
                - match_callback: 'origin: cdn.jsdelivr.net'
                  strategy: 'CacheFirst'
                  preload_urls: # Optional, but you are now sure the library is preloaded even if used on another page the user never met before
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/js/onsenui.min.js'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/ionicons/css/ionicons.min.css'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/onsen-css-components.min.css'
```

**Comment by Spomky** [comment]
Hi,

I tested and you have to set the scheme+domain.

```yaml
                - match_callback: 'origin: https://cdn.jsdelivr.net'
                  strategy: 'CacheFirst'
                  preload_urls:
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/js/onsenui.min.js'
```

in my header I set that:
```html
<script type="module" src="https://cdn.jsdelivr.net/npm/onsenui@2.12.8/js/onsenui.min.js"></script>
<script type="module" src="https://cdn.jsdelivr.net/npm/@simplewebauthn/browser@13.1.2/dist/bundle/index.umd.min.js"></script>
```

And I can see the SW handling the requests. Also the one that is not preloaded is present in the cache meaning the SW successfully cached it.

<img width="1096" height="345" alt="Image" src="https://github.com/user-attachments/assets/01bcdc1f-80fc-43cf-a2fa-634b31c64384" />

Closing as I modified the page in the documentation.
