### ISSUE TITLE
Preloaded URLs generator

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#154]
### Description

The preloaded URLs for resource caching is very simple: it is a list of URLs or route names with/without params.
It can be difficult or boring to list all possible values.
For example, let's imagine an application with 4 features. The application is served in 3 differents languages.
The configuraiton file will looks like as follows:

```yaml
pwa:
    serviceworker:
        wokrbox:
            resource_caches:
                preload_urls:
                  - path: 'app_features'
                  - params:
                        _locale: 'en'
                        feature: 'feature1'
                  - path: 'app_features'
                  - params:
                        _locale: 'jp'
                        feature: 'feature1'
                  - path: 'app_features'
                  - params:
                        _locale: 'it'
                        feature: 'feature1'
...
```

We could imagine a service that will generate the URLs for us. Each application will be free to manipulate that list depending on its needs.

### Example

```yaml
pwa:
    serviceworker:
        wokrbox:
            resource_caches:
                preload_urls:
                  - id: "preloaded_urls_features_service"
...
```

```php
interface UrlGenerator
{
    /**
     * @return iterable<Url>
     */
    public function generateUrls(): iterable;
}
```

```php
final readonly class PreloadUrlsForFeatures implements UrlGenerator
{
    public function generateUrls(): iterable
    {
        foreach($locales as $locale) {
            foreach($features as $feature) {
                yield ... // Generate a SpomkyLabs\PwaBundle\Dto\Url here
            }
        }
    }
}
```
