### ISSUE TITLE
Bad screenshot type yaml configuration

### ISSUE THREAD

**Issue by davidromani** [Spomky-Labs/phpwa#171]
### Version(s) affected

1.1.4

### Description

Screenshot `type` config parameter doesn't works.

### How to reproduce

```yaml
pwa:
    manifest:
        enabled: true
        screenshots:
            -
                src: 'screenshots/screenshot-desktop-1.png'
                platform: 'macos'
                label: 'Landing page'
                form_factor: 'wide'
                type: 'image/png'
```

### Possible Solution

It seems that for now only works if you write `format` instead of `type`. Fix the related documentation [here](https://pwa.spomky-labs.com/the-manifest/screenshots#type-parameter)
