### ISSUE TITLE
subdomain support: dynamic manifest 

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#173]
### Description

I'm working on a project where I'd like separate PWAs for each project, which are set by subdomain.  Each project will have its own logo, shortname, etc.

It is possible to make the manifest a template?  

### Example

```yaml
pwa:
    image_processor: 'pwa.image_processor.imagick'
    manifest:
        enabled: true
        background_color: "#c026d3"
        theme_color: "#c026d3"
        name: '{{ project.name }}'
        short_name: '{{ project.shortName }}'
        description: '{{ project.description }}'
        orientation: "any"
```

Similarly for the icons and screenshots.

Then https://project1.example.com/manifest.json would get the project from the subdomain and populate it accordingly.
