### ISSUE TITLE
match_callback: 'origin: cdn.jsdelivr.net' not working as expected.

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#191]
### Version(s) affected

1.2.x

### Description

I'm moving this from #148 because I think it's a bug or perhaps the documentation can be improved.

```yaml
                - match_callback: 'origin: cdn.jsdelivr.net'
                  strategy: 'CacheFirst' # or CacheOnly
                  preload_urls: 
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/js/onsenui.min.js'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/ionicons/css/ionicons.min.css'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/onsen-css-components.min.css'
```

This library never changes, so I really just want to cache it once when the application starts up.

It does not appear that this is working, though, as the other assets show that they are delivered via the service worker, but not the jsdelivr ones.

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/7f698ea2-87be-4b5f-ad92-dded673e7698)

### How to reproduce

Go to 

https://pwa-last-stack.survos.com/en/mobile/start

and look at the console network

**Comment by Spomky** [comment]
Hello @tacman,

Can you try with `match_callback: 'origin: https://cdn.jsdelivr.net'`?
It looks like [the function is using the scheme](https://developer.mozilla.org/en-US/docs/Web/API/URL/origin) as well.

**Comment by tacman** [comment]
On a related note, I'd like to make sure my s3 urls are cached and/or preloaded.  We launched an audio-tour last night, but the exhibition was an old stone building with lousy internet, a perfect application for pre-fetching.  There was good internet at the entrance, in the ideal world they'd have gotten all the images and audio at the entrance when they first installed it.

**Comment by tacman** [comment]
> Can you try with `match_callback: 'origin: https://cdn.jsdelivr.net'`?

No, that created lots of errors.  Lemme add this to a demo repo that has s3 and jsdelivr urls that need to be cached.  Thanks!

**Comment by tacman** [comment]
What is the difference between workbox-strategy and StrategyHandler?

![image](https://github.com/Spomky-Labs/pwa-bundle/assets/619585/f4e2a8d5-0ef6-44a1-a1ba-d2d859b2c0a2)

In this case, I've setup 

```yaml
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
            resource_caches:
                - match_callback: 'origin: cdn.jsdelivr.net'
                  strategy: 'CacheOnly'
                  preload_urls: # Optional, but you are now sure the library is preloaded even if used on another page the user never met before
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/js/onsenui.min.js'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/ionicons/css/ionicons.min.css'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/onsen-css-components.min.css'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/material-design-iconic-font/fonts/Material-Design-Iconic-Font.woff2?v=2.2.0'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/material-design-iconic-font/css/material-design-iconic-font.min.css'
                      - 'https://cdn.jsdelivr.net/npm/onsenui@2.12.8/css/font_awesome/webfonts/fa-brands-400.woff2'

```
