### ISSUE TITLE
Allow Manifest to leverage on Favicons features

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#210]
### Description

The Manifest icons are just icons that are resized depending on the size list.
It should leverage on the Favicons features where the scale, background color or border radius can be set.

### Example

```yaml
pwa:
    favicons:
        enabled: true
        src: "images/todo.svg"
        background_color: "#c3d7f7"
        image_scale: 66
        border_radius: 50
    manifest:
        enabled: true
        icons:
            - src: "images/todo.svg"
              sizes: "any"
        icons:
            - src: "@favicons"
              purpose: "maskable"
              format: "png"
              sizes: [32, 64, 128, 256, 512]
```

With the special keyword `@favicons`, the bundle will use the icon and options set in favicons.
