### ISSUE TITLE
iOS Splash Screens

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#223]
### Description

Allow the iOS Splash Screens to be generated like favicons.
See https://medium.com/@applification/progressive-web-app-splash-screens-80340b45d210

### Example

```
pwa:
    favicons:
        splash:
            src: '....'
```
