### ISSUE TITLE
phpwa as key doesn't work

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#23]
### Version(s) affected

1.0

### Description

Following the README instructions, using phpwa as the config key didn't work, but usa pwa (the alias) did.

### How to reproduce

```yaml
# config/packages/phpwa.yaml
phpwa:
    name: 'My App'
```

### Possible Solution

```yaml
# config/packages/phpwa.yaml
pwa:
    name: 'My App'
```
