### ISSUE TITLE
exclude cached reources not working

### ISSUE THREAD

**Issue by davidromani** [Spomky-Labs/phpwa#230]
### Version(s) affected

1.2.x

### Description

Due to an old discussion https://github.com/Spomky-Labs/pwa-bundle/discussions/109 @Spomky has discovered a problem inside code.

### How to reproduce

```yaml
# config/packages/pwa.yaml
pwa:
    serviceworker:
        enabled: true
        src: 'sw.js'
        workbox:
            enabled: true
            cache_manifest: false
            asset_cache:
                regex: '/^(?!\/assets\/bundles\/).*\.(css|js|json|xml|txt|map|ico|png|jpe?g|gif|svg|webp|bmp)$/'
            image_cache:
                enabled: false
            resource_caches:
                -
                    match_callback: "({request, url}) => (url.pathname.startsWith('/') && !url.pathname.startsWith('/assets'))"
                    cache_name: 'navigation'
                    strategy: 'NetworkFirst'
                    network_timeout: 1
                    preload_urls:
                        - '@static_pages'
```

Set this asset_cache value is not working due that /assets/bundles resources are being always cached (see screenshot).

<img width="1497" alt="Captura de pantalla 2024-08-09 a les 15 53 55" src="https://github.com/user-attachments/assets/363e1ea4-f0df-4a79-940d-832cca5b30ed">
