### ISSUE TITLE
workbox/workbox-window.prod.mjs not loading

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#238]
### Version(s) affected

1.3.x (and ^1.2)

### Description

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts

https://ff.survos.com/workbox/workbox-window.prod.mjs

### How to reproduce

https://ff.survos.com/events/index

I'm trying to debug why this doesn't have an "Install" option in the debug tools.  Perhaps it's related to the above error with the workbox not being loaded.

### Additional Context

# pwa.yaml

```yaml
pwa:
    image_processor: 'pwa.image_processor.imagick'
#    favicons:
#        enabled: true
#        src: assets/icons/symfony.svg

    manifest:
        enabled: true
        background_color: "#c026d3"
        theme_color: "#c026d3"
        name: 'Foothills Forum Photo collection'
        short_name: 'ff-photos'
        description: 'Foothills Forum Photo collection allows users to submit photos of local high school sporting events in Rappahannock'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        id: "/"
        start_url: "/"
        icons:
#            - https://www.svgrepo.com/svg/522368/camera
            - src: "images/camera-svgrepo-com.svg"
              sizes: any
#            - src: "images/space-planet-icon.svg"
#              sizes: any

        screenshots:
            - src: screenshots/screenshot-1200x1100.png
              width: 1200
              height: 1100
              format: image/png

        categories: []
        shortcuts: []
        edge_side_panel:
            preferred_width: 280
        widgets: []
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
#            resource_caches:
#                - cache_name: page
#                  strategy: staleWhileRevalidate
#                  regex: 'what-should-this-becopose'
#                  urls:
#    #                    - {path: "app_planet_show", params: {id: 5}}
#                        - 'app_homepage'
#                        - 'app_terms'
#            offline_fallback:
#                page: 'app_homepage'
##                page: 'app_offline_page'
##                    image: 'images/offline.svg'
##                        font: 'fonts/normal.ttf'
```
