### ISSUE TITLE
Unit tests not running (or passing)

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#249]
### Version(s) affected

1.2.x

### Description

It looks like unit tests have been disabled.

https://github.com/Spomky-Labs/pwa-bundle/actions/workflows/tests.yml

### How to reproduce

They are failing locally, too.

```
vendor/bin/phpunit 
PHPUnit 11.4.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.3.13
Configuration: /home/tac/g/tacman/pwa-bundle/phpunit.xml.dist

F............FF                                                   15 / 15 (100%)

Time: 00:00.169, Memory: 30.00 MB

There were 6 failures:

1) SpomkyLabs\PwaBundle\Tests\Functional\CompileCommandTest::theFileAreCompiled
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:35
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:21

2) SpomkyLabs\PwaBundle\Tests\Functional\CompileCommandTest::theFileAreCompiled
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:35
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:29

3) SpomkyLabs\PwaBundle\Tests\Functional\GenerateIconsCommandTest::iconsAreCorrectlyCreated
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:35
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:21

4) SpomkyLabs\PwaBundle\Tests\Functional\GenerateIconsCommandTest::iconsAreCorrectlyCreated
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:35
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:29

5) SpomkyLabs\PwaBundle\Tests\Functional\TakeScreenshotCommandTest::aScreenshotIsCorrectlyTake
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:35
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:21

6) SpomkyLabs\PwaBundle\Tests\Functional\TakeScreenshotCommandTest::aScreenshotIsCorrectlyTake
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:35
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:29

FAILURES!
Tests: 15, Assertions: 17, Failures: 6.
```

**Comment by Spomky** [comment]
Closing this as fixed now.
Thanks

**Comment by tacman** [comment]
Tests in 1.3.x aren't yet working:

```bash
git clone git@github.com:Spomky-Labs/pwa-bundle.git && cd pwa-bundle
composer install
vendor/bin/phpunit 
```

```
PHPUnit 12.0.9 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.4.3
Configuration: /home/tac/g/tacman/pwa-bundle/phpunit.xml.dist

F............FF                                                   15 / 15 (100%)

Time: 00:00.356, Memory: 47.50 MB

There were 6 failures:

1) SpomkyLabs\PwaBundle\Tests\Functional\CompileCommandTest::theFileAreCompiled
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:22

2) SpomkyLabs\PwaBundle\Tests\Functional\CompileCommandTest::theFileAreCompiled
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:30

3) SpomkyLabs\PwaBundle\Tests\Functional\GenerateIconsCommandTest::iconsAreCorrectlyCreated
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:22

4) SpomkyLabs\PwaBundle\Tests\Functional\GenerateIconsCommandTest::iconsAreCorrectlyCreated
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:30

5) SpomkyLabs\PwaBundle\Tests\Functional\TakeScreenshotCommandTest::aScreenshotIsCorrectlyTaken
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:22

6) SpomkyLabs\PwaBundle\Tests\Functional\TakeScreenshotCommandTest::aScreenshotIsCorrectlyTaken
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:30

FAILURES!
Tests: 15, Assertions: 17, Failures: 6.
~/g/tacman/pwa-bundle$ 
```

**Comment by tacman** [comment]
Nor in 1.2.x

```bash
git checkout 1.2.x
composer install
```

```
~/g/tacman/pwa-bundle$ vendor/bin/phpunit 
PHPUnit 11.5.14 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.4.3
Configuration: /home/tac/g/tacman/pwa-bundle/phpunit.xml.dist

F..........EEFF                                                   15 / 15 (100%)

Time: 00:00.072, Memory: 24.00 MB

There were 2 errors:

1) SpomkyLabs\PwaBundle\Tests\Functional\DevServerTest::theManifestIsServed
Error: Class "SpomkyLabs\PwaBundle\Service\IconResolver" not found

/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:406
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:346
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:1161
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/getErrorHandler_ErrorRenderer_SerializerService.php:23
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:103
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/getErrorControllerService.php:21
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:103
/home/tac/g/tacman/pwa-bundle/vendor/symfony/dependency-injection/Container.php:221
/home/tac/g/tacman/pwa-bundle/vendor/symfony/dependency-injection/Container.php:203
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:38
/home/tac/g/tacman/pwa-bundle/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:25
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/Controller/ControllerResolver.php:115
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/Controller/ControllerResolver.php:95
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernel.php:166
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernel.php:76
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/EventListener/ErrorListener.php:97
/home/tac/g/tacman/pwa-bundle/vendor/symfony/event-dispatcher/EventDispatcher.php:246
/home/tac/g/tacman/pwa-bundle/vendor/symfony/event-dispatcher/EventDispatcher.php:206
/home/tac/g/tacman/pwa-bundle/vendor/symfony/event-dispatcher/EventDispatcher.php:56
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernel.php:241
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernel.php:91
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/Kernel.php:182
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernelBrowser.php:62
/home/tac/g/tacman/pwa-bundle/vendor/symfony/framework-bundle/KernelBrowser.php:157
/home/tac/g/tacman/pwa-bundle/vendor/symfony/browser-kit/AbstractBrowser.php:378
/home/tac/g/tacman/pwa-bundle/tests/Functional/DevServerTest.php:23

2) SpomkyLabs\PwaBundle\Tests\Functional\DevServerTest::theServiceWorkerIsServed
Error: Class "SpomkyLabs\PwaBundle\Service\IconResolver" not found

/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:406
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:346
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:1161
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/getErrorHandler_ErrorRenderer_SerializerService.php:23
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:92
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/getErrorControllerService.php:21
/home/tac/g/tacman/pwa-bundle/var/cache/test/ContainerLyFPx82/SpomkyLabs_PwaBundle_Tests_AppKernelTestContainer.php:92
/home/tac/g/tacman/pwa-bundle/vendor/symfony/dependency-injection/Container.php:221
/home/tac/g/tacman/pwa-bundle/vendor/symfony/dependency-injection/Container.php:203
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/Controller/ContainerControllerResolver.php:38
/home/tac/g/tacman/pwa-bundle/vendor/symfony/framework-bundle/Controller/ControllerResolver.php:25
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/Controller/ControllerResolver.php:115
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/Controller/ControllerResolver.php:95
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernel.php:166
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernel.php:76
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/EventListener/ErrorListener.php:97
/home/tac/g/tacman/pwa-bundle/vendor/symfony/event-dispatcher/EventDispatcher.php:246
/home/tac/g/tacman/pwa-bundle/vendor/symfony/event-dispatcher/EventDispatcher.php:206
/home/tac/g/tacman/pwa-bundle/vendor/symfony/event-dispatcher/EventDispatcher.php:56
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernel.php:241
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernel.php:91
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/Kernel.php:182
/home/tac/g/tacman/pwa-bundle/vendor/symfony/http-kernel/HttpKernelBrowser.php:62
/home/tac/g/tacman/pwa-bundle/vendor/symfony/framework-bundle/KernelBrowser.php:157
/home/tac/g/tacman/pwa-bundle/vendor/symfony/browser-kit/AbstractBrowser.php:378
/home/tac/g/tacman/pwa-bundle/tests/Functional/DevServerTest.php:37

--

There were 6 failures:

1) SpomkyLabs\PwaBundle\Tests\Functional\CompileCommandTest::theFileAreCompiled
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:22

2) SpomkyLabs\PwaBundle\Tests\Functional\CompileCommandTest::theFileAreCompiled
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:30

3) SpomkyLabs\PwaBundle\Tests\Functional\GenerateIconsCommandTest::iconsAreCorrectlyCreated
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:22

4) SpomkyLabs\PwaBundle\Tests\Functional\GenerateIconsCommandTest::iconsAreCorrectlyCreated
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:30

5) SpomkyLabs\PwaBundle\Tests\Functional\TakeScreenshotCommandTest::aScreenshotIsCorrectlyTake
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:22

6) SpomkyLabs\PwaBundle\Tests\Functional\TakeScreenshotCommandTest::aScreenshotIsCorrectlyTake
assert(self::$kernel !== null)

/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:36
/home/tac/g/tacman/pwa-bundle/tests/Functional/AbstractPwaTestCase.php:30

ERRORS!
Tests: 15, Assertions: 13, Errors: 2, Failures: 6.
```

**Comment by Spomky** [comment]
It works fine here.
As the failing tests are related to the image/icon management and as you also have similar issues with the images on your project, I am pretty sure it has something in common with your setup.

What is the output of this command: `php -m | grep -e "json" -e "mbstring" -e "gd" -e "curl" -e "imagick"`?

![Image](https://github.com/user-attachments/assets/f6873039-a268-4901-a044-4050680e16d8)

**Comment by tacman** [comment]
```bash
php -m | grep -e "json" -e "mbstring" -e "gd" -e "curl" -e "imagick"
curl
gd
imagick
json
mbstring
```

I'm running 8.4, i looks like you're running 8.3

```bash
hp -v
PHP 8.4.3 (cli) (built: Jan 19 2025 14:20:34) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.3, Copyright (c), by Zend Technologies
```

**Comment by Spomky** [comment]
No differences with PHP 8.4

![Image](https://github.com/user-attachments/assets/0e7ce24c-83f5-4d44-9453-e80b0389dab4)

**Comment by Spomky** [comment]
When you run the demo, do you still have 5xx status codes in the profiler?

**Comment by tacman** [comment]
Yes, for the icons:

![Image](https://github.com/user-attachments/assets/9583ce48-df9a-4e2e-888a-ffa967991a45)

**Comment by tacman** [comment]
Ah, this might be it!

![Image](https://github.com/user-attachments/assets/ddf591c4-90fa-4649-a5cf-cf7107ad49df)

**Comment by tacman** [comment]
```bash
identify -list format | grep SVG
     MSVG  SVG       rw+   ImageMagick's own SVG internal renderer
      SVG  SVG       rw+   Scalable Vector Graphics (XML 2.9.14)
     SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.14)
```

**Comment by Spomky** [comment]
It looks like you are using GD and it does not seem to support SVG files.
Can you switch to Imagick and tell me if it solves this problem?

```yaml
pwa:
    image_processor: 'pwa.image_processor.imagick'
```

**Comment by Spomky** [comment]
~Looks like some it can be solved by installing `libmagickcore-6*`~

**Comment by tacman** [comment]
No change.  I tried gd and got a new error:

![Image](https://github.com/user-attachments/assets/913f1db4-8689-4c3f-a468-971e7fbcd6a9)

```yaml
pwa:
#    image_processor: 'pwa.image_processor.imagick'
    image_processor: 'pwa.image_processor.gd'
    #logger: 'App\Service\PwaLogger'
#    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'
    favicons:
        enabled: true
        src: "images/pwabundlelogo.svg"
        tile_color: "#FCFCFC"
        use_start_image: true
    manifest:
        enabled: true
        public_url: '/pwa/site.{locale}.webmanifest'
        background_color: "#FCFCFC"
        theme_color: "#BE202F"
        name: 'app.name'
        short_name: 'app.short_name'
        description: 'app.description'
        orientation: "any"
        display: "standalone"
        scope: "/"
        display_override: ['fullscreen', 'minimal-ui', 'window-controls-overlay']
        id: "pwa-bundle-today"
        start_url: "app.start_url"
        icons:
            - src: "images/pwabundlelogo.svg"
              format: 'png'
              sizes: [48, 96, 128, 144, 192, 256, 384, 512]
              purpose: 'any'
            - src: "images/pwabundlelogo.svg"
              format: 'png'
              sizes: [48, 96, 128, 144, 192, 256, 384, 512]
              image_scale: 50
              background_color: "#c3d7f7"
              purpose: 'maskable'
        screenshots:
            - src: "images/wide.png"
              format: 'png'
              label: "The homepage"
            - src: "images/narrow.png"
              format: 'png'
              label: "The homepage"
        categories:
            - "education"
            - "utilities"
        shortcuts:
            - name: "app.features.geolocation.name"
              short_name: "app.features.geolocation.short_name"
              description: "app.features.geolocation.description"
              url: 'app_feature_geolocation'
        edge_side_panel:
            preferred_width: 280
        widgets: []
        related_applications: []
    serviceworker:
        enabled: true
        src: "sw.js"
        skip_waiting: true
        workbox:
            enabled: true
            resource_caches:
                - match_callback: 'startsWith: /videos/'
                  cache_name: 'videos'
                  strategy: 'CacheFirst'
                - match_callback: 'navigate'
                  cache_name: 'pages'
                  strategy: 'NetworkFirst'
                  network_timeout: 2
                  preload_urls:
                      - '@pages'
#        background_fetch:
#            enabled: true
#            success_message: 'Your download is ready!'
#            failure_message: 'Your download failed! Please try again.'
```
