### ISSUE TITLE
Multiple manifests in a single application

### ISSUE THREAD

**Issue by tacman** [Spomky-Labs/phpwa#286]
### Description

I'm not sure if this is a feature request or if it already exists if it's a documentation request.  I had proposed events in #173 , but this question is more about if it's possible rather than using events as a solution.

I have a multi-tenant application, and I want to configure the manifest according to each tenant.  In particular, the application variables need to change according to each project.

### Example

```yaml
projects:
    acme:
        pwa:
            manifest:
                enabled: true
                name: "Acme"
                short_name: "ACME"
                start_url: "/acme/index.html"
                display: "standalone"
                background_color: "#ffffff"
                theme_color: "#4285f4"
    abc:
        pwa:
            manifest:
                enabled: true
                name: "ABC Project"
                short_name: "abc"
                start_url: "/abc/index.html"
                display: "standalone"
                background_color: "#eeeddd"
                theme_color: "#4285f4"
    ```

The landing page would handle which manifest to load, e.g. myapplication.com/abc 

Stepping back, maybe there's another way to get the end result.  Each project is an audio-tour for a gallery or museum.  The gallery wants to put a QR code up next to the objects that open a PWA with their look and feel (and content, of course).   That's doable with the web interface, but is it possible to do at the PWA level? 

Alternatively, perhaps there's a way to configure just the application icons and links, so that on the users mobile device, they see a logo for "abc" and it open "myapplication.com/abc" but the installation and manifest are all for the main application.
