### ISSUE TITLE
Allow custom manifest parameters

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#29]
### Description

It could be interesting to allow custom manifest key-values.
These parameters will be just put as they are in the manifest file.

### Example

```yaml
pwa:
    custom:
        foo: ["bar", "baz"]
```
