### ISSUE TITLE
Manifest icons not served by asset mapper

### ISSUE THREAD

**Issue by davidm-glitch** [Spomky-Labs/phpwa#293]
### Version(s) affected

1.2.5

### Description

I encountered an issue where the icons specified in the pwa.yaml for the manifest aren't being delivered to the frontend via the asset mapper. Only the exact paths from the yaml file appear.

Symfony Version: 7.2.5
Asset-Mapper Version: 7.2.5

This is my pwa.yaml

```yaml
pwa:
    manifest:
        enabled: true
        scope: "/"
        name: "App-Name"
        short_name: "App-Name"
        start_url: "/"
        display: "standalone"
        background_color: "#232e3a"
        theme_color: "#232e3a"
        dir: "ltr"
        lang: "de"
        orientation: "portrait-primary"
        icons:
            -   src: images/pwa/icon-16x16.png
                sizes:
                    - 16
                type: image/png
            -   src: images/pwa/icon-32x32.png
                sizes:
                    - 32
                type: image/png
            -   src: images/pwa/icon-48x48.png
                sizes:
                    - 48
                type: image/png
            -   src: images/pwa/icon-96x96.png
                sizes:
                    - 96
                type: image/png
            -   src: images/pwa/icon-144x144.png
                sizes:
                    - 144
                type: image/png
            -   src: images/pwa/icon-180x180.png
                sizes:
                    - 180
                type: image/png
            -   src: images/pwa/icon-256x256.png
                sizes:
                    - 256
                type: image/png
            -   src: images/pwa/icon-512x512.png
                sizes:
                    - 512
                type: image/png
            -   src: images/pwa/icon-1024x1024.png
                sizes:
                    - 1024
                type: image/png

    favicons:
        enabled: true
        src: images/pwa/icon.png
    image_processor: 'pwa.image_processor.gd'
```

The Output inside the template is the following

```html
<link rel="manifest" href="/site.webmanifest" crossorigin="use-credentials">
<link rel="icon" sizes="16x16" href="images/pwa/icon-16x16.png" type="image/png">
<link rel="icon" sizes="32x32" href="images/pwa/icon-32x32.png" type="image/png">
<link rel="icon" sizes="48x48" href="images/pwa/icon-48x48.png" type="image/png">
<link rel="icon" sizes="96x96" href="images/pwa/icon-96x96.png" type="image/png">
<link rel="icon" sizes="144x144" href="images/pwa/icon-144x144.png" type="image/png">
<link rel="icon" sizes="180x180" href="images/pwa/icon-180x180.png" type="image/png">
<link rel="icon" sizes="256x256" href="images/pwa/icon-256x256.png" type="image/png">
<link rel="icon" sizes="512x512" href="images/pwa/icon-512x512.png" type="image/png">
<link rel="icon" sizes="1024x1024" href="images/pwa/icon-1024x1024.png" type="image/png">
<link rel="icon" sizes="16x16" type="image/x-icon" href="/favicon.ico">
<link rel="icon" sizes="16x16" type="image/png" href="/favicons/icon-16x16-9fdd8dc2b638edce88cf19216c30b5f0.png">
<link rel="icon" sizes="32x32" type="image/png" href="/favicons/icon-32x32-aff76e104ed2d5981196c8ff8b59287d.png">
<link rel="apple-touch-icon" sizes="180x180" type="image/png" href="/favicons/icon-180x180-8fbd8018eee3b169f2340e2209e4daac.png">
<link rel="icon" sizes="192x192" type="image/png" href="/favicons/icon-192x192-0f9936436621ede391e8f1d4fcc88fac.png">
<link rel="icon" sizes="512x512" type="image/png" href="/favicons/icon-512x512-48e8d1e604ac71bfb9a67bd62d565646.png">
<meta name="theme-color" content="#232e3a">
```

As you can see, the favicons are working fine, the icons dont come with an asset mapper path. 

Interestingly, the output is displayed correctly in the profiler.

![Image](https://github.com/user-attachments/assets/6760b3b2-06ba-4e14-9257-7a473453c52f)

![Image](https://github.com/user-attachments/assets/eed15529-bde5-41fc-9efc-0acd27884d07)

### How to reproduce

Install asset-mapper & pwa-bundle 1.2, setup pwa.yaml as shown above. Icons must be located inside assets/images/pwa. 

### Additional Context

While browsing the documentation, I noticed that the link to "Asset Mapper Resource" doesn't lead to anything.

[->](https://pwa.spomky-labs.com/the-manifest/icons#src-parameter)

**Comment by davidm-glitch** [comment]
And, as is usually the case, you'll find the solution shortly after submitting.

If you remove the `type: image/png` from the pwa.yaml, everything works as it should, and the icons are delivered by the asset mapper.

The source of this information is the [icon generation](https://pwa.spomky-labs.com/image-management/icons#resizing-icons):


When creating the icons with the symfony console command pwa:create:icons, you get a configuration output. This output includes the type. This is also stated in the documentation.

**Comment by Spomky** [comment]
Hi,

Thank you for this issue.
I will investigate on this.

**Comment by Spomky** [comment]
By the way, the following configuration is sufficient.
You can specify all sizes at once. The type is only needed when you convert from one type to another (e.g. svg => png)

```yaml
pwa:
    manifest:
        enabled: true
        scope: "/"
        name: "App-Name"
        short_name: "App-Name"
        start_url: "/"
        display: "standalone"
        background_color: "#232e3a"
        theme_color: "#232e3a"
        dir: "ltr"
        lang: "de"
        orientation: "portrait-primary"
        icons:
            -   src: images/pwa/icon.png
                sizes: [16, 32, 48, 96, 144, 180, 256, 512, 1024]

    favicons:
        enabled: true
        src: images/pwa/icon.png
    image_processor: 'pwa.image_processor.gd'
```
