### ISSUE TITLE
Selective cache cleaning

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#304]
### Description

At the moment, when the SW is updated, the entire cache is cleared.
This may cause issues
* when the developers declared specific cache
* this requires the entire cache to be recreated

An option could be added at the `clear_cache` optinon at the cache resource level instead of globally.

### Example

```yaml
#Before
pwa:
    serviceworker:
        enabled: true
        workbox:
            clear_cache: true #default value

#After

pwa:
    serviceworker:
        enabled: true
        workbox:
            asset_cache:
                enabled: true
                clear_cache: true
                regex: '/\.(css|jsx?)$/'
            resource_caches:
                - match_callback: 'startsWith: /pages/'
                  cache_name: 'static-pages'
                  clear_cache: false
                  strategy: 'NetworkFirst'
```
