### ISSUE TITLE
Dark and Light icons

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#306]
### Description

It could be great to distinguish Light and Dark icons so that the meta tag is something like that:
```html
<link rel="shortcut icon" href="./images/favicon-dark.png" media="(prefers-color-scheme: dark)" />
<link rel="shortcut icon" href="./images/favicon-light.png" media="(prefers-color-scheme: light)" />
```

### Example

```yaml
pwa:
    favicons:
        enabled: true
        src: "icons/light-icon.svg"
        dark-src: "icons/dark-icon.svg"
```
