### ISSUE TITLE
Better icons mgmt

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/phpwa#45]
### Description

At the moment, the icons must exist as an asset to be linked to the Manifest file.
Without changing the configuration, it could be great to generate them on-the-fly when compiled

### Example

```yaml
pwa:
    icons:
        - src: "images/pwa/favicon.svg"
          sizes: [48]
          format: 'ico'
        - src: "images/pwa/favicon.svg"
          sizes: [96, 128, 256, 512, 1024]
          format: 'png'
        - src: "images/pwa/favicon.svg"
          sizes: [0]
        - src: "images/pwa/favicon.svg"
          purpose: 'maskable'
          sizes: [0]
```

*Note that only 1 asset really exist*

Manifest file in dev/prod
```json
{
    "icons": [
        {
            "src": "/assets/pwa/favicon-xxxhashxxx.ico",
            "format": "image/ico"
            "sizes": "48x48"
        },
        {
            "src": "/assets/pwa/favicon-xxxhashxxx.png",
            "format": "image/png",
            "sizes": "96x96 128x128 256x256 512x512 1024x1024"
        },
        {
            "src": "/assets/pwa/favicon-xxxhashxxx.svg",
            "format": "image/svg",
            "sizes": "any"
        },
        {
            "src": "/assets/pwa/favicon-xxxhashxxx.svg",
            "format": "image/svg",
            "purpose": "maskable",
            "sizes": "any"
        }
    ]
}
```
